name: Build osu-tracker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for release'
        required: true
        default: 'v0.0.0'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: osu-tracker
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [release]
        architecture: [x86]  # Only target x86 (32-bit)
        c_compiler: [gcc, cl]
        cpp_compiler: [g++, cl]
        include:
          - os: ubuntu-latest
            build_type: release
            preset: x86-release-linux
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            build_type: release
            preset: x86-release-windows
            c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: cl
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: cl
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: cl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: List files in osu-tracker directory
        run: ls -R ${{ github.workspace }}/osu-tracker

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev zlib1g-dev libx11-dev mesa-common-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev build-essential xorg-dev libglu1-mesa-dev wayland-protocols libwayland-dev libxkbcommon-dev wayland-scanner++

      - name: Install CMake
        uses: lukka/get-cmake@v4.0.1

      - name: Set up MSVC environment
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x86
      - name: Install Meson and Ninja on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install meson==1.3.2 ninja==1.11.1

      - name: Configure-Linux
        if: runner.os == 'Linux'
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: '/home/runner/work/osu-tracker/osu-tracker/src/CMakeLists.txt'
          configurePreset: '${{ matrix.preset }}'
      
      - name: Configure-Windows
        if: runner.os == 'Windows'
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: 'D:\a\osu-tracker\osu-tracker\src\CMakeLists.txt'
          configurePreset: '${{ matrix.preset }}'
        env:
          VCPKG_ROOT:
      
      - name: Build-Linux
        if: runner.os == 'Linux'
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: '/home/runner/work/osu-tracker/osu-tracker/src/CMakeLists.txt'
          buildPreset: '${{ matrix.preset }}'

      - name: Build-Windows
        if: runner.os == 'Windows'
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: 'D:\a\osu-tracker\osu-tracker\src\CMakeLists.txt'
          buildPreset: '${{ matrix.preset }}'
        env:
          VCPKG_ROOT:

      - name: Zip Linux Release Artifact
        if: runner.os == 'Linux'
        run: |
          cd /home/runner/work/osu-tracker/osu-tracker/src/out/build/x86-release-linux
          zip -r /home/runner/work/osu-tracker/osu-tracker/src/out/x86-release-linux.zip osu-tracker

      - name: Zip Windows Release Artifact
        if: runner.os == 'Windows'
        run: powershell -Command "Compress-Archive -Path 'D:\a\osu-tracker\osu-tracker\src\out\build\x86-release-windows\osu-tracker*' -DestinationPath 'D:\a\osu-tracker\osu-tracker\src\out\x86-release-windows.zip'"

      - name: Upload Linux Release Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: x86-release-linux
          path: '/home/runner/work/osu-tracker/osu-tracker/src/out/x86-release-linux.zip'

      - name: Upload Windows Release Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: x86-release-windows
          path: 'D:/a/osu-tracker/osu-tracker/src/out/x86-release-windows.zip'

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Linux zip
        uses: actions/download-artifact@v4
        with:
          name: x86-release-linux
          path: ./release-artifacts/linux

      - name: Download Windows zip
        uses: actions/download-artifact@v4
        with:
          name: x86-release-windows
          path: ./release-artifacts/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: |
            ./release-artifacts/linux/x86-release-linux.zip
            ./release-artifacts/windows/x86-release-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
